### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by webtop**
README: Add instruction to disable IP hiding in chrome.

Change-type: minor
Signed-off-by: Paul Allsopp pallsopp@gmail.com

### CODE REVIEW

**Comment by mbalamat** [comment]
@webtop can you change your commit message, this is why the check above failed? We have a specific way of writing the commit messages (which I need to add in the README, sorry, my bad). 
```
README: Add instruction to disable IP hiding in chrome.

Change-type: minor
Signed-off-by: <Your Name> <Your email>
```

eg https://github.com/balenalabs/balena-cam/commit/54c7397ef9861c3bf16bc5a26d57d8d064786cac

**Comment by mbalamat** [comment]
@webtop by changing the commit message I meant to do something like `git commit --amend` and then change that to the text you used above and push that. I took the liberty to do that for you, preserving your contribution. Is this ok by you?

**Comment by mbalamat** [comment]
@balena-ci retest

**Comment by pallsopp** [comment]
My apologies, I realized that afterwards and just hadn't gotten back to it. Thanks for the change.

**Comment by mbalamat** [comment]
@webtop thanks for the PR, I'll merge.

**Pull request merged**
